using System; using UnityEngine; using UnityEngine.Rendering;
namespace Gravivore.Presentation.AudioVfx {
[DisallowMultipleComponent] public sealed class Phase6BVfxInstance:MonoBehaviour {
[SerializeField] Phase6BVfxCue _cue; [SerializeField] Phase6BVfxShape _shape; [SerializeField,Min(.04f)] float _duration=.18f; [SerializeField] Color _color=new(.22f,.9f,1,.8f); [SerializeField,Range(1,64)] int _particleCount=12; [SerializeField,Min(.05f)] float _range=4; [SerializeField,Min(.005f)] float _width=.055f; [SerializeField,Range(5,170)] float _angleDegrees=58; [SerializeField] Material _material;
LineRenderer _line; ParticleSystem _particles; float _remaining,_activeDuration; Vector3 _origin,_destination; bool _built;
public Phase6BVfxCue Cue=>_cue; public int ParticleCount=>_particleCount; public Material Material=>_material; public bool IsPlaying=>_remaining>0&&gameObject.activeSelf;
void Awake()=>EnsureBuilt(); void Update()=>Tick(Time.deltaTime); void OnDisable()=>_remaining=0;
public void Play(Vector3 origin,Vector3 destination,float durationOverride=-1){EnsureBuilt();_origin=origin;_destination=destination;transform.position=origin;_activeDuration=durationOverride>0?durationOverride:_duration;_remaining=_activeDuration;gameObject.SetActive(true);if(_line!=null)ConfigureLine(0);if(_particles!=null){_particles.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);_particles.Emit(Mathf.Clamp(_particleCount,1,64));}}
public void Tick(float dt){if(_remaining<=0||!gameObject.activeSelf)return;_remaining=Mathf.Max(0,_remaining-Mathf.Max(0,dt));if(_line!=null)ConfigureLine(1-_remaining/Mathf.Max(.0001f,_activeDuration));if(_remaining<=0){if(_particles!=null)_particles.Stop(true,ParticleSystemStopBehavior.StopEmitting);gameObject.SetActive(false);}}
public void StopImmediate(){_remaining=0;if(_particles!=null)_particles.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);gameObject.SetActive(false);}
public void ValidateOrThrow(){if(_duration<=0||_particleCount<1||_particleCount>64||_range<=0||_width<=0)throw new InvalidOperationException($"{name}: invalid VFX limits.");if(_material==null)throw new InvalidOperationException($"{name}: material missing.");}
static bool UsesLine(Phase6BVfxShape s)=>s==Phase6BVfxShape.Beam||s==Phase6BVfxShape.Circle||s==Phase6BVfxShape.Cone||s==Phase6BVfxShape.Line||s==Phase6BVfxShape.Scanner;
void EnsureBuilt(){if(_built)return;ValidateOrThrow();if(UsesLine(_shape))BuildLine();else BuildParticles();_built=true;}
void BuildLine(){var go=new GameObject("Phase 6B Geometry",typeof(LineRenderer));go.transform.SetParent(transform,false);_line=go.GetComponent<LineRenderer>();_line.useWorldSpace=true;_line.widthMultiplier=_width;_line.numCapVertices=2;_line.numCornerVertices=2;_line.shadowCastingMode=ShadowCastingMode.Off;_line.receiveShadows=false;_line.lightProbeUsage=LightProbeUsage.Off;_line.reflectionProbeUsage=ReflectionProbeUsage.Off;_line.sharedMaterial=_material;}
void BuildParticles(){var go=new GameObject("Phase 6B Particles",typeof(ParticleSystem));go.transform.SetParent(transform,false);_particles=go.GetComponent<ParticleSystem>();var m=_particles.main;m.playOnAwake=false;m.loop=false;m.duration=Mathf.Max(.05f,_duration);m.startLifetime=Mathf.Min(_duration,_shape==Phase6BVfxShape.Sparks?.28f:.18f);m.startColor=_color;m.maxParticles=Mathf.Clamp(_particleCount,1,64);m.simulationSpace=ParticleSystemSimulationSpace.World;m.startSize=_shape==Phase6BVfxShape.Burst?.16f:.07f;m.startSpeed=_shape==Phase6BVfxShape.Charge?-.7f:_shape==Phase6BVfxShape.Sparks?2.3f:1.4f;m.gravityModifier=_shape==Phase6BVfxShape.Sparks?.35f:0;var e=_particles.emission;e.enabled=false;var sh=_particles.shape;sh.enabled=true;sh.shapeType=_shape==Phase6BVfxShape.Sparks?ParticleSystemShapeType.Cone:ParticleSystemShapeType.Sphere;sh.radius=_shape==Phase6BVfxShape.Charge?.42f:.08f;if(_shape==Phase6BVfxShape.Sparks)sh.angle=22;var r=_particles.GetComponent<ParticleSystemRenderer>();r.sharedMaterial=_material;r.renderMode=ParticleSystemRenderMode.Billboard;r.shadowCastingMode=ShadowCastingMode.Off;r.receiveShadows=false;r.lightProbeUsage=LightProbeUsage.Off;r.reflectionProbeUsage=ReflectionProbeUsage.Off;}
void ConfigureLine(float n){var c=_color;c.a*=Mathf.Clamp01(1-n);_line.startColor=c;_line.endColor=new Color(c.r,c.g,c.b,c.a*.55f);_line.widthMultiplier=_width;if(_shape==Phase6BVfxShape.Beam||_shape==Phase6BVfxShape.Line){_line.loop=false;_line.positionCount=2;_line.SetPosition(0,_origin);_line.SetPosition(1,(_destination-_origin).sqrMagnitude>.0001f?_destination:_origin+transform.forward*_range);return;}if(_shape==Phase6BVfxShape.Cone){ConfigureCone(20);return;}ConfigureRing(_shape==Phase6BVfxShape.Scanner?Mathf.Lerp(.2f,_range,n):_range,32);}
void ConfigureRing(float radius,int segments){_line.loop=true;_line.positionCount=segments;for(var i=0;i<segments;i++){var a=i*Mathf.PI*2/segments;_line.SetPosition(i,_origin+new Vector3(Mathf.Cos(a)*radius,.03f,Mathf.Sin(a)*radius));}}
void ConfigureCone(int segments){_line.loop=true;_line.positionCount=segments+2;_line.SetPosition(0,_origin);var half=_angleDegrees*.5f;for(var i=0;i<=segments;i++){var a=Mathf.Lerp(-half,half,i/(float)segments);var d=Quaternion.Euler(0,a,0)*transform.forward;_line.SetPosition(i+1,_origin+d*_range+Vector3.up*.03f);}}
}}
