using System; using System.Collections.Generic; using UnityEngine;
namespace Gravivore.Presentation.AudioVfx {
[CreateAssetMenu(menuName="Gravivore/Presentation/Phase 6B Audio Bank",fileName="Phase6B_AudioBank")]
public sealed class Phase6BAudioBank:ScriptableObject {
[Serializable] private sealed class Entry { [SerializeField] Phase6BAudioCue _cue; [SerializeField] AudioClip[] _clips=Array.Empty<AudioClip>(); [SerializeField,Range(0,1)] float _volume=.8f; [SerializeField] Vector2 _pitchRange=Vector2.one; [SerializeField,Range(0,1)] float _spatialBlend=.35f; [SerializeField] bool _loop; public Phase6BAudioCue Cue=>_cue; public AudioClip[] Clips=>_clips; public float Volume=>_volume; public Vector2 PitchRange=>_pitchRange; public float SpatialBlend=>_spatialBlend; public bool Loop=>_loop; }
[SerializeField] Entry[] _entries=Array.Empty<Entry>(); public int EntryCount=>_entries?.Length??0;
public bool TryResolve(Phase6BAudioCue cue,int seed,out Phase6BAudioSelection selection){if(_entries!=null)foreach(var e in _entries){if(e==null||e.Cue!=cue)continue;var clips=e.Clips;if(clips==null||clips.Length==0)break;var h=unchecked(seed*397^(int)cue*7919)&0x7fffffff;var clip=clips[h%clips.Length];if(clip==null)break;selection=new Phase6BAudioSelection(clip,Mathf.Clamp01(e.Volume),Mathf.Lerp(e.PitchRange.x,e.PitchRange.y,h/(float)int.MaxValue),Mathf.Clamp01(e.SpatialBlend),e.Loop);return true;}selection=default;return false;}
public void ValidateOrThrow(){if(_entries==null)throw new InvalidOperationException("Phase 6B audio entries missing.");var seen=new HashSet<Phase6BAudioCue>();foreach(var e in _entries){if(e==null)throw new InvalidOperationException("Null audio entry.");if(!seen.Add(e.Cue))throw new InvalidOperationException($"Duplicate cue {e.Cue}.");if(e.Clips==null||e.Clips.Length==0)throw new InvalidOperationException($"Cue {e.Cue} has no clips.");foreach(var c in e.Clips)if(c==null)throw new InvalidOperationException($"Cue {e.Cue} has missing clip.");if(e.PitchRange.x<=0||e.PitchRange.y<e.PitchRange.x)throw new InvalidOperationException($"Cue {e.Cue} pitch invalid.");}}
}}
