using System;using UnityEngine;
namespace Gravivore.Presentation.AudioVfx {
[DisallowMultipleComponent] public sealed class Phase6BReviewDriver:MonoBehaviour {
[SerializeField] Phase6BAudioBank _audioBank; [SerializeField] Phase6BVfxPool.Binding[] _vfxBindings=Array.Empty<Phase6BVfxPool.Binding>(); Phase6BAudioPlayer _audio; Phase6BVfxPool _vfx;float _clock;int _step;bool _running;static readonly float[] Times={0,.46f,.52f,.64f,1.25f,1.62f,2.15f,3,3.85f,4.7f,4.82f,5.35f};
public void Configure(Phase6BAudioBank bank,Phase6BVfxPool.Binding[] bindings){_audioBank=bank;_vfxBindings=bindings??Array.Empty<Phase6BVfxPool.Binding>();}
void Start(){var a=new GameObject("Phase 6B Review Audio",typeof(Phase6BAudioPlayer));a.transform.SetParent(transform,false);_audio=a.GetComponent<Phase6BAudioPlayer>();if(_audioBank!=null)_audio.Initialize(_audioBank,6);var v=new GameObject("Phase 6B Review VFX",typeof(Phase6BVfxPool));v.transform.SetParent(transform,false);_vfx=v.GetComponent<Phase6BVfxPool>();if(_vfxBindings.Length>0)_vfx.Initialize(_vfxBindings);Replay();}
void Update(){if(!_running)return;_clock+=Time.deltaTime;while(_step<Times.Length&&_clock>=Times[_step])Trigger(_step++);if(_step>=Times.Length&&_clock>6.4f){_audio?.StopAll();_vfx?.StopAll();_running=false;}}
public void Replay(){_audio?.StopAll();_vfx?.StopAll();_clock=0;_step=0;_running=true;}
void Trigger(int i){var l=transform.position+Vector3.left*3.2f;var c=transform.position;var r=transform.position+Vector3.right*3.2f;switch(i){case 0:_audio?.TryPlay(Phase6BAudioCue.GravityLashCharge,l);_vfx?.TryPlay(Phase6BVfxCue.PlayerCharge,l,l+Vector3.forward*3,.46f);break;case 1:_audio?.TryPlay(Phase6BAudioCue.GravityLashRelease,l);_vfx?.TryPlay(Phase6BVfxCue.PlayerReleaseFlash,l,l+Vector3.forward*4);break;case 2:_vfx?.TryPlay(Phase6BVfxCue.GravityLashTravel,l,l+Vector3.forward*4);break;case 3:_audio?.TryPlay(Phase6BAudioCue.GravityLashImpact,l+Vector3.forward*4);_vfx?.TryPlay(Phase6BVfxCue.PlayerImpact,l+Vector3.forward*4,l);break;case 4:_audio?.TryPlay(Phase6BAudioCue.EnemyMechanicalHit,c,1);_vfx?.TryPlay(Phase6BVfxCue.HostileImpact,c,c);break;case 5:_audio?.TryPlay(Phase6BAudioCue.EnemyShutdown,c,2);_vfx?.TryPlay(Phase6BVfxCue.MechanicalKillBurst,c,c);break;case 6:_audio?.TryPlay(Phase6BAudioCue.CustodianCone,r);_vfx?.TryPlay(Phase6BVfxCue.BossConeTelegraph,r,r+Vector3.forward*4,.7f);break;case 7:_audio?.TryPlay(Phase6BAudioCue.CustodianLine,r);_vfx?.TryPlay(Phase6BVfxCue.BossLineTelegraph,r,r+Vector3.forward*5,.7f);break;case 8:_audio?.TryPlay(Phase6BAudioCue.CustodianCircle,r);_vfx?.TryPlay(Phase6BVfxCue.BossCircleTelegraph,r,r,.7f);break;case 9:_audio?.TryPlay(Phase6BAudioCue.RepairHub,c);_vfx?.TryPlay(Phase6BVfxCue.RepairBeam,c+Vector3.left,c+Vector3.right);break;case 10:_vfx?.TryPlay(Phase6BVfxCue.WeldingSparks,c+Vector3.right,c);break;case 11:_vfx?.TryPlay(Phase6BVfxCue.ScannerSweep,c,c,.65f);break;}}
}}
