using System.Linq;using Gravivore.Editor.AudioVfx;using Gravivore.Presentation.AudioVfx;using NUnit.Framework;using UnityEditor;using UnityEngine;using Object=UnityEngine.Object;
namespace Gravivore.Tests.EditMode {
public sealed class Phase6BAudioVfxProductionTests {
const string R="Assets/_Game/Content/Presentation/Phase6B/VFX/Prefabs";
[Test] public void AudioBankComplete(){var b=AssetDatabase.LoadAssetAtPath<Phase6BAudioBank>(Phase6BProductionPackBuilder.AudioBankPath);Assert.IsNotNull(b);Assert.DoesNotThrow(b.ValidateOrThrow);Assert.That(b.EntryCount,Is.GreaterThanOrEqualTo(16));foreach(var g in AssetDatabase.FindAssets("t:AudioClip",new[]{"Assets/_Game/Content/Presentation/Phase6B/Audio"})){var c=AssetDatabase.LoadAssetAtPath<AudioClip>(AssetDatabase.GUIDToAssetPath(g));Assert.That(c.channels,Is.EqualTo(1),c.name);Assert.That(c.frequency,Is.EqualTo(48000),c.name);Assert.That(c.length,Is.GreaterThan(.08f),c.name);}}
[Test] public void MissingOptionalAudioGraceful(){var b=ScriptableObject.CreateInstance<Phase6BAudioBank>();var serialized=new SerializedObject(b);var entries=serialized.FindProperty("_entries");entries.arraySize=1;var entry=entries.GetArrayElementAtIndex(0);entry.FindPropertyRelative("_cue").enumValueIndex=(int)Phase6BAudioCue.GravityLashImpact;var clips=entry.FindPropertyRelative("_clips");clips.arraySize=1;clips.GetArrayElementAtIndex(0).objectReferenceValue=null;serialized.ApplyModifiedPropertiesWithoutUndo();var go=new GameObject("Audio Test",typeof(Phase6BAudioPlayer));try{var p=go.GetComponent<Phase6BAudioPlayer>();Assert.DoesNotThrow(()=>p.Initialize(b,2));Assert.IsFalse(p.TryPlay(Phase6BAudioCue.GravityLashImpact,Vector3.zero));}finally{Object.DestroyImmediate(go);Object.DestroyImmediate(b);}}
[Test] public void VfxPrefabsSafe(){var gs=AssetDatabase.FindAssets("t:Prefab",new[]{R});Assert.That(gs.Length,Is.GreaterThanOrEqualTo(13));foreach(var g in gs){var p=AssetDatabase.GUIDToAssetPath(g);var go=AssetDatabase.LoadAssetAtPath<GameObject>(p);Assert.IsNull(go.GetComponentInChildren<Collider>(true),p);Assert.IsNull(go.GetComponentInChildren<Rigidbody>(true),p);Assert.IsNull(go.GetComponentInChildren<Camera>(true),p);Assert.IsNull(go.GetComponentInChildren<Light>(true),p);Assert.That(go.GetComponentsInChildren<MonoBehaviour>(true).All(x=>x is Phase6BVfxInstance),Is.True,p);var fx=go.GetComponent<Phase6BVfxInstance>();Assert.That(fx.ParticleCount,Is.InRange(1,64));Assert.IsNotNull(fx.Material);Assert.DoesNotThrow(fx.ValidateOrThrow);}}
[Test] public void PoolBounded(){var fx=AssetDatabase.LoadAssetAtPath<GameObject>($"{R}/PFX_PlayerImpact.prefab").GetComponent<Phase6BVfxInstance>();var go=new GameObject("Pool",typeof(Phase6BVfxPool));try{var p=go.GetComponent<Phase6BVfxPool>();p.Initialize(new[]{new Phase6BVfxPool.Binding(Phase6BVfxCue.PlayerImpact,fx,2)});Assert.That(p.CreatedInstanceCount,Is.EqualTo(2));p.TryPlay(Phase6BVfxCue.PlayerImpact,Vector3.zero,Vector3.forward);p.TryPlay(Phase6BVfxCue.PlayerImpact,Vector3.right,Vector3.forward);p.TryPlay(Phase6BVfxCue.PlayerImpact,Vector3.left,Vector3.forward);Assert.That(p.CreatedInstanceCount,Is.EqualTo(2));Assert.That(p.ActiveCount,Is.LessThanOrEqualTo(2));}finally{Object.DestroyImmediate(go);}}
[Test] public void BuilderValidation()=>Assert.DoesNotThrow(Phase6BProductionPackBuilder.Validate);
}}
