using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.Rendering;

namespace Gravivore.VisualReplacementProofV1
{
    public sealed partial class VisualReplacementProofBootstrap
    {
        private IEnumerator CaptureReviewSet()
        {
            yield return null;
            yield return null;

            var outputPath = ResolveOutputDirectory();
            Directory.CreateDirectory(outputPath);

            WriteMetrics(Path.Combine(outputPath, "MobileMetrics.md"));

            yield return CaptureFrame("01_G0_GameCamera.png", _g0Root, new Vector3(-2.65f, 2.05f, -2.15f), false, false, true, false);
            yield return CaptureFrame("02_Scout_GameCamera.png", _scoutRoot, new Vector3(2.25f, 1.05f, -0.25f), false, false, false, true);
            yield return CaptureFrame("03_SecondEnemy_GameCamera.png", _cutterRoot, new Vector3(1.1f, 0.95f, 4.35f), false, false, false, false, true);
            yield return CaptureFrame("04_G0_Vs_Scout.png", null, new Vector3(-0.2f, 1.35f, -0.85f), false, false, true, true);
            yield return CaptureFrame("05_CombatArea_GameCamera.png", null, new Vector3(0f, 1.15f, 1.55f), false, false, true, true, true);
            yield return CaptureFrame("06_ReactorAndProps.png", _reactorRoot, new Vector3(3.6f, 1.45f, 5.7f), false, false);
            yield return CaptureFrame("07_WallBarrierFamily.png", _barrierRoot, new Vector3(-1.2f, 1.05f, 8.0f), false, false);
            yield return CaptureFrame("08_Combat_Readability.png", null, new Vector3(-0.15f, 1.30f, -0.8f), true, false, true, true);
            yield return CaptureFrame("09_Death_Readability.png", null, new Vector3(1.55f, 1.15f, 0.1f), false, true, false, true);
            yield return CaptureFrame("10_Wide_Proof_Area.png", null, new Vector3(0f, 1.10f, 2.15f), false, false, true, true, true);

            SetActorVisibility(true, true, true);
            _environmentRoot.gameObject.SetActive(true);
            _attackProxyRoot.gameObject.SetActive(false);
            _deathProxyRoot.gameObject.SetActive(false);
            AimCamera(new Vector3(0f, 1.30f, 1.4f));

            Debug.Log("[VisualReplacementProofV1] Captured review frames and metrics to: " + outputPath);
        }

        private IEnumerator CaptureFrame(
            string fileName,
            Transform focus,
            Vector3 target,
            bool attackProxy,
            bool deathProxy,
            bool showG0 = false,
            bool showScout = false,
            bool showCutter = false)
        {
            SetActorVisibility(showG0, showScout, showCutter);
            _environmentRoot.gameObject.SetActive(true);
            _attackProxyRoot.gameObject.SetActive(attackProxy);
            _deathProxyRoot.gameObject.SetActive(deathProxy);

            if (focus != null)
            {
                focus.gameObject.SetActive(true);
            }

            AimCamera(target);
            yield return null;
            RenderFrame(Path.Combine(ResolveOutputDirectory(), fileName));
        }

        private void RenderFrame(string path)
        {
            const int width = 1080;
            const int height = 1920;

            var renderTexture = new RenderTexture(width, height, 24, RenderTextureFormat.ARGB32)
            {
                name = "VRP1_ReviewCapture",
                antiAliasing = 1
            };

            var previousTarget = _reviewCamera.targetTexture;
            var previousActive = RenderTexture.active;

            try
            {
                _reviewCamera.targetTexture = renderTexture;
                RenderTexture.active = renderTexture;
                _reviewCamera.Render();

                var texture = new Texture2D(width, height, TextureFormat.RGB24, false, false);
                texture.ReadPixels(new Rect(0f, 0f, width, height), 0, 0, false);
                texture.Apply(false, false);
                File.WriteAllBytes(path, texture.EncodeToPNG());
                Destroy(texture);
            }
            finally
            {
                _reviewCamera.targetTexture = previousTarget;
                RenderTexture.active = previousActive;
                renderTexture.Release();
                Destroy(renderTexture);
            }
        }

        private void WriteMetrics(string path)
        {
            var lines = new List<string>
            {
                "# Visual Replacement Proof V1 — measured runtime metrics",
                "",
                "Generated by the isolated proof scene from the actual constructed meshes.",
                "",
                "| Actor | Triangles | Renderers | Material slots | Unique materials | Texture sizes | Mesh mode | Animation clips |",
                "|---|---:|---:|---:|---:|---|---|---:|"
            };

            lines.Add(MetricRow("G-0", _g0Root));
            lines.Add(MetricRow("Scout", _scoutRoot));
            lines.Add(MetricRow("Cutter", _cutterRoot));
            lines.Add("");
            lines.Add("Surface variation is generated deterministically at runtime (128–256 px) for selected armor/metal/floor materials. There are **0 imported texture bytes** and no third-party texture license dependency.");
            lines.Add("All actor renderers are static MeshRenderer/MeshFilter renderers; V1 contains no SkinnedMeshRenderer and no animation clips.");
            lines.Add("The proof intentionally measures presentation geometry only. It is not wired into Chapter01 or gameplay.");

            File.WriteAllLines(path, lines);
        }

        private string MetricRow(string label, Transform root)
        {
            var filters = root.GetComponentsInChildren<MeshFilter>(true);
            var renderers = root.GetComponentsInChildren<Renderer>(true);
            long triangleCount = 0;

            foreach (var filter in filters)
            {
                var mesh = filter.sharedMesh;
                if (mesh != null)
                {
                    triangleCount += mesh.triangles.LongLength / 3L;
                }
            }

            var materialSlots = renderers.Sum(r => r.sharedMaterials != null ? r.sharedMaterials.Length : 0);
            var actorMaterials = renderers
                .SelectMany(r => r.sharedMaterials ?? Array.Empty<Material>())
                .Where(m => m != null)
                .Distinct()
                .ToArray();
            var uniqueMaterialCount = actorMaterials.Length;
            var textureSizes = actorMaterials
                .Select(m => m.GetTexture("_BaseMap") as Texture2D)
                .Where(t => t != null && t.name.StartsWith("VRP1_", StringComparison.Ordinal))
                .Select(t => t.width + "x" + t.height)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(v => v, StringComparer.Ordinal)
                .ToArray();
            var textureSummary = textureSizes.Length == 0 ? "none" : string.Join(", ", textureSizes);

            return $"| {label} | {triangleCount} | {renderers.Length} | {materialSlots} | {uniqueMaterialCount} | {textureSummary} procedural | static MeshFilter | 0 |";
        }

        private void SetActorVisibility(bool g0, bool scout, bool cutter)
        {
            _g0Root.gameObject.SetActive(g0);
            _scoutRoot.gameObject.SetActive(scout);
            _cutterRoot.gameObject.SetActive(cutter);
        }

        private void AimCamera(Vector3 target)
        {
            _reviewCamera.transform.position = target + MandatoryCameraOffset;
            _reviewCamera.transform.rotation = Quaternion.LookRotation(target - _reviewCamera.transform.position, Vector3.up);
            _reviewCamera.fieldOfView = CameraFov;
        }

        private string ResolveOutputDirectory()
        {
            var projectRoot = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
            return Path.GetFullPath(Path.Combine(projectRoot, outputDirectory));
        }

        private GameObject NewRoot(string name)
        {
            var go = new GameObject(name);
            go.transform.SetParent(transform, false);
            return go;
        }

        private static Transform NewSocket(Transform parent, string name, Vector3 localPosition)
        {
            var socket = new GameObject(name).transform;
            socket.SetParent(parent, false);
            socket.localPosition = localPosition;
            socket.localRotation = Quaternion.identity;
            return socket;
        }

        private void AddLoft(Transform parent, string name, IReadOnlyList<VisualProofMeshFactory.LoftRing> rings, int sides, Vector3 localPosition, Quaternion localRotation, string material)
        {
            AddMesh(parent, name, VisualProofMeshFactory.CreateLoft("VRP1_" + name, rings, sides), localPosition, localRotation, material);
        }

        private void AddExtruded(Transform parent, string name, IReadOnlyList<Vector2> polygon, float depth, Vector3 localPosition, Quaternion localRotation, string material)
        {
            AddMesh(parent, name, VisualProofMeshFactory.CreateExtrudedPolygon("VRP1_" + name, polygon, depth), localPosition, localRotation, material);
        }

        private void AddTube(Transform parent, string name, IReadOnlyList<Vector3> points, float radius, int sides, string material)
        {
            AddMesh(parent, name, VisualProofMeshFactory.CreateTube("VRP1_" + name, points, radius, sides), Vector3.zero, Quaternion.identity, material);
        }

        private void AddTorus(Transform parent, string name, float majorRadius, float minorRadius, int majorSegments, int minorSegments, Vector3 localPosition, Quaternion localRotation, string material)
        {
            AddMesh(parent, name, VisualProofMeshFactory.CreateTorus("VRP1_" + name, majorRadius, minorRadius, majorSegments, minorSegments), localPosition, localRotation, material);
        }

        private void AddMesh(Transform parent, string name, Mesh mesh, Vector3 localPosition, Quaternion localRotation, string material)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);
            go.transform.localPosition = localPosition;
            go.transform.localRotation = localRotation;
            var filter = go.AddComponent<MeshFilter>();
            filter.sharedMesh = mesh;
            var renderer = go.AddComponent<MeshRenderer>();
            renderer.sharedMaterial = _materials[material];
            renderer.shadowCastingMode = ShadowCastingMode.On;
            renderer.receiveShadows = true;
        }

        private static VisualProofMeshFactory.LoftRing Ring(float y, float x, float z, float offsetX = 0f, float offsetZ = 0f, float rotationDegrees = 0f)
        {
            return new VisualProofMeshFactory.LoftRing(y, x, z, offsetX, offsetZ, rotationDegrees);
        }

        private static Vector2[] ChamferedPolygon(float width, float height, float chamfer)
        {
            var x = width * 0.5f;
            var y = height * 0.5f;
            var c = Mathf.Clamp(chamfer, 0.001f, Mathf.Min(x, y) * 0.45f);
            return new[] { new Vector2(-x + c, -y), new Vector2(x - c, -y), new Vector2(x, -y + c), new Vector2(x, y - c), new Vector2(x - c, y), new Vector2(-x + c, y), new Vector2(-x, y - c), new Vector2(-x, -y + c) };
        }

        private static Vector2[] BladePolygon(float length, float height)
        {
            return new[] { new Vector2(-length * 0.5f, -height * 0.5f), new Vector2(length * 0.30f, -height * 0.34f), new Vector2(length * 0.5f, 0f), new Vector2(length * 0.30f, height * 0.34f), new Vector2(-length * 0.5f, height * 0.5f) };
        }

        private static string SideName(float side, string suffix) => (side < 0f ? "Left_" : "Right_") + suffix;
    }
}
